ExpensePlanner/Controllers/ExpenseController.cs
using ExpensePlanner.Models;
using ExpensePlanner.Models.Dtos;
using ExpensePlanner.Services;
using ExpensePlanner.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExpensePlanner.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly int userId = StaticService.userId;

        public ExpenseController(IExpenseService expenseService)
        {
            _expenseService = expenseService;
        }

        /// <summary>
        /// Akcja wyswietlajaca bledy
        /// </summary>
        /// <returns></returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /// <summary>
        /// Akcja wyświetlająca liste obiektów(wydatków)
        /// </summary>
        /// <returns></returns>
        public IActionResult Get()
        {
            TempData["IsAdmin"] = _expenseService.IsAdmin(userId);
            TempData["IsLogged"] = true;

            var result = _expenseService.Get(userId);

            return View(result);
        }

        /// <summary>
        /// Akcja dodająca obiekt(wydatek) do bazy
        /// </summary>
        /// <param name="expense"></param>
        /// <returns></returns>
        public IActionResult Post(ExpenseDto expense)
        {
            TempData["IsAdmin"] = _expenseService.IsAdmin(userId);

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(nameof(expense.Amount), "Wrong data type in Amount");
                TempData["IsLogged"] = true;
                return View(expense);
            }

			_expenseService.Post(expense, userId);

            return RedirectToAction("Get");
        }

        /// <summary>
        /// Akcja usuwająca obiekt(wydatek) z bazy
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(int id)
        {            
            TempData["IsLogged"] = true;

            _expenseService.Delete(id);

            return RedirectToAction("Get");
        }

        /// <summary>
        /// Akcja wyswietlająca liste wydatków zrealizowanych
        /// </summary>
        /// <returns></returns>
        public IActionResult GetCompleted()
        {
            TempData["IsAdmin"] = _expenseService.IsAdmin(userId);
            TempData["IsLogged"] = true;

            var result = _expenseService.GetCompleted(userId);

            return View(result);
        }

        /// <summary>
        /// Akcja oznaczająca wybrany obiekt(wydatek) jako zrealizowany
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("/MarkAsDone/{id}")]
        public IActionResult MarkAsDone(int id)
        {            
            TempData["IsLogged"] = true;

            _expenseService.MarkAsDone(id);

            return RedirectToAction("Get");
        }

    }
}

ExpensePlanner/Controllers/UserController.cs
using ExpensePlanner.Models;
using ExpensePlanner.Services;
using ExpensePlanner.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ExpensePlanner.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly int userId = StaticService.userId;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        /// <summary>
        /// Akcja usuwająca użytkownika
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Delete(int id)
        {
            TempData["IsLogged"] = true;

            if (_userService.DeleteUser(id))
            {
                return RedirectToAction("Get");
            }

            return BadRequest();
        }

        /// <summary>
        /// Akcja wyświetlająca liste użytkowników
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            TempData["IsAdmin"] = _userService.IsAdmin(userId);
            TempData["IsLogged"] = true;

            var allUsers = _userService.GetAllUser().ToList();

            return View(allUsers);
        }

        /// <summary>
        /// Akcja wyświetlająca obiekty(wydatki) innego użytkownika
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> GetUserExpenses(int Id)
        {
            TempData["IsAdmin"] = _userService.IsAdmin(userId);
            TempData["IsLogged"] = true;

            var userExpenses = _userService.GetUserExpenses(Id);

            return View(userExpenses);
        }
    }
}

ExpensePlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpensePlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpensePlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Expense" asp-action="Get">ExpensePlanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if((bool)TempData["IsLogged"])
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Get">Expense</a>
                            </li>

                            @if ((bool)TempData["IsAdmin"])
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Get">Users</a>
                                </li>
                            }
                        }
                         else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RegisterUser">Register</a>
                            </li>                             
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ExpensePlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>